### PR TITLE
Add MAIA schema

### PR DESCRIPTION
**Pull request by madbaron**
This PR adds the MAIA schema to ACTSTracking.
The material map, detector geometry description and root TGeo model are added to the data folder.

### CODE REVIEW

**Comment by pandreetto** [comment]
Hi Federico

It seems to me that this part of the patch for GeometryIdMappingTool.cxx
----
     break;
     case VertexBarrel:
-      if (det_type == GeometryIdMappingTool::DetSchema::MuColl_v1) layer_id = 2 * (layerID + 1);
-      else layer_id = layerID + 2; 
+      if (det_type == GeometryIdMappingTool::DetSchema::MAIA_v0){
+        if(layerID==0) layer_id = 2;
+        if(layerID==1) layer_id = 4;
+        if(layerID==2) layer_id = 6;
+        if(layerID==4) layer_id = 8;
+        if(layerID==6) layer_id = 10;
       break;
+    }
     case InnerTrackerBarrel:
     case OuterTrackerBarrel: {
----
removes any reference to MuColl and MuSIC detector.
Could you confirm, please?
Thanks

**Comment by madbaron** [comment]
Hi Paolo,

thanks for checking!
Indeed I must have accidentally removed two lines when merging my local version of ACTSTracking.

Could you take another look and let me know if you spot anything else?

**Comment by pandreetto** [comment]
With this patch:
```
diff --git a/data/CMakeLists.txt b/data/CMakeLists.txt
index d4f65ce..80e4373 100644
--- a/data/CMakeLists.txt
+++ b/data/CMakeLists.txt
@@ -1,9 +1,9 @@
 # Tracking geometry
-INSTALL(FILES MuColl_v1.root MuSIC_v1.root MuSIC_v2.root
+INSTALL(FILES MuColl_v1.root MuSIC_v1.root MuSIC_v2.root MAIA_v0.root
   DESTINATION ${CMAKE_INSTALL_DATADIR}/ACTSTracking/data)
 
 # Geometry description
-INSTALL(FILES MuColl_v1.json MuSIC_v1.json MuSIC_v2.json
+INSTALL(FILES MuColl_v1.json MuSIC_v1.json MuSIC_v2.json MAIA_v0.json
   DESTINATION ${CMAKE_INSTALL_DATADIR}/ACTSTracking/data)
 
 # Material map
```
the configuration is perfect. We can merge the request.

**Comment by madbaron** [comment]
Thanks again for the very quick turnaround!

Merging!

**Pull request merged**
